### ISSUE TITLE
Legend and Layers boxes could be bigger

### ISSUE THREAD

**Issue by crvanpollard** [rbeatty1/BCHMP#16]
I feel that the Legend box could be larger to show more items as well as full legends for several layers.
Desired Typical Cross Section is one example.
Same could be said for the Layers .
This would require some tweaks but the logo's could simply stay on the map like on the initial page load

**Comment by rbeatty1** [comment]
I'm going to close this—these are things that have been discussed extensively throughout the development process with the entire project team and this is the sizing and layout that was settled upon
